version: "3.9"
services:
  backend:
    container_name: backendflask
    build: .
    ports:
      - "5000:5000"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ./dockerfile
    depends_on:
            - backend  
    restart: always
    ports:
      - "80:80"


  